name: Wiz_Scanner_For_IaC
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    secrets:
      wiz_client_id:
        required: true
      wiz_client_secret:
        required: true
jobs:
  IaC-Wiz-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
      - name: Install Wizcli
        run: |
          sudo curl -Lo wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64
          sudo chmod +x wizcli
          sudo mv wizcli /usr/local/bin
      - name: Authenticate and Run Wiz Scan
        env:
          WIZ_CLIENT_ID: ${{ secrets.wiz_client_id }}
          WIZ_CLIENT_SECRET: ${{ secrets.wiz_client_secret }}
        run: |
          wizcli auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET
          wizcli iac scan --path .


